name: haskell-project
version: 0.1.0.0
license: BSD3
maintainer: "r.w.qaisir@se22.qmul.ac.uk"

extra-source-files:
  - README.md
  - CHANGELOG.md


# ONLY MODIFY THIS! DONT MODIFY .CABAL DIRECTLY, IT WILL GET TRUNCATED!
dependencies:
  - base >= 4.7 && < 5
  - aeson
  - yaml
  - http-conduit
  - http-client
  - sqlite-simple
  - text
  - bytestring
  - Cabal

library:
  source-dirs: src

executables:
  haskell-project-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-project

tests:
  haskell-project-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-project