name: haskell-project
version: 0.1.0.0
license: BSD3
author: "Raees Qaisir"
maintainer: "r.w.qaisir@se22.qmul.ac.uk"
copyright: "2022 Raees Qaisir"

extra-source-files:
  - README.md
  - CHANGELOG.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/mfpx/haskell-project#readme>

# ONLY MODIFY THIS! DONT MODIFY .CABAL DIRECTLY, IT WILL GET TRUNCATED!
dependencies:
  - base >= 4.7 && < 5
  - aeson
  - yaml
  - http-conduit
  - http-client
  - sqlite-simple
  - text
  - bytestring
  - Cabal

library:
  source-dirs: src

executables:
  haskell-project-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-project

tests:
  haskell-project-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-project